//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HumanaApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HumanaEntities : DbContext
    {
        public HumanaEntities()
            : base("name=HumanaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblClaimsdata> tblClaimsdatas { get; set; }
        public virtual DbSet<tblExcelfile> tblExcelfiles { get; set; }
        public virtual DbSet<tblemployee> tblemployees { get; set; }
    }
}
