//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HumanaApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblClaimsdata
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> ProcessDate { get; set; }
        public string AuditID { get; set; }
        public string ProcessorName { get; set; }
        public string BatchNo { get; set; }
        public string Leads { get; set; }
        public string ClientID { get; set; }
        public Nullable<decimal> TotalChargeAmount { get; set; }
        public Nullable<decimal> TotalPaidAmount { get; set; }
        public string Claimnumber { get; set; }
        public string OriginalCorrectedClaim { get; set; }
        public string Auditor { get; set; }
        public Nullable<System.DateTime> AuditDate { get; set; }
        public Nullable<bool> IHT_nonIHT { get; set; }
        public string ErrorComment { get; set; }
        public string ErrorType { get; set; }
        public string OverUnderPayment { get; set; }
        public string ErrorCode { get; set; }
        public string ErrorCategory { get; set; }
        public string ErrorSubCategory { get; set; }
        public string CorrectionStatus { get; set; }
        public string RebuttalComment { get; set; }
        public string AuditorAgreeDisagreeonRebuttal { get; set; }
        public string Auditorcommentifdisagree { get; set; }
        public string AssignName { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Comments { get; set; }
        public string Status { get; set; }
    }
}
