//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HumanaApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblemployee
    {
        public int Id { get; set; }
        public string DAS_ID { get; set; }
        public string NESSIE_ID { get; set; }
        public string SS_ID { get; set; }
        public string Name__Sortable_ { get; set; }
        public string GCM_Levels { get; set; }
        public string Designation { get; set; }
        public Nullable<System.DateTime> Hire_Date { get; set; }
        public string Position { get; set; }
        public string Gender { get; set; }
        public string Master_Cost_Center { get; set; }
        public string Organizational_Unit { get; set; }
        public string Organizational_Unit_Description { get; set; }
        public string WBS_Code { get; set; }
        public string WBS_Description_ { get; set; }
        public string PID_ { get; set; }
        public string Project_Name { get; set; }
        public string Sub_Verticals { get; set; }
        public string Sub_Functions { get; set; }
        public string Company_Name { get; set; }
        public string Entity { get; set; }
        public string Functions__Ops_Support_ { get; set; }
        public string Billability_Status { get; set; }
        public string Reporting_Manager_SAP_ID { get; set; }
        public string Reporting_Manager { get; set; }
        public string Country { get; set; }
        public string Location { get; set; }
        public string Curr__Loc__HR_Mngr { get; set; }
        public string E_Mail_Address { get; set; }
        public string SS_E_Mail_Address { get; set; }
    }
}
